package com.assignment.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Resident Name")
	private java.lang.String residentName;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.Character type;

	@org.kie.api.definition.type.Label("Hoa Approval")
	private java.lang.Character hoaApproval;

	@org.kie.api.definition.type.Label("Structural Permit")
	private java.lang.Boolean structuralPermit;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label(value = "Electrical Permit")
	private java.lang.Boolean electricalPermit;

	public NewOrder() {
	}

	public java.lang.String getResidentName() {
		return this.residentName;
	}

	public void setResidentName(java.lang.String residentName) {
		this.residentName = residentName;
	}

	public java.lang.Character getType() {
		return this.type;
	}

	public void setType(java.lang.Character type) {
		this.type = type;
	}

	public java.lang.Character getHoaApproval() {
		return this.hoaApproval;
	}

	public void setHoaApproval(java.lang.Character hoaApproval) {
		this.hoaApproval = hoaApproval;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Boolean getAllPermitApproved() {
		return this.structuralPermit && this.electricalPermit;
	}

	public NewOrder(java.lang.Character hoaApproval,
			java.lang.Boolean electricalPermit,
			java.lang.Boolean structuralPermit, java.lang.String status,
			java.lang.String residentName) {
		this.hoaApproval = hoaApproval;
		this.electricalPermit = electricalPermit;
		this.structuralPermit = structuralPermit;
		this.status = status;
		this.residentName = residentName;
	}

	public NewOrder(java.lang.String residentName,
			java.lang.Character hoaApproval, java.lang.Boolean electricalPermit,
			java.lang.Boolean structuralPermit, java.lang.String status,
			java.lang.Character type) {
		this.residentName = residentName;
		this.hoaApproval = hoaApproval;
		this.electricalPermit = electricalPermit;
		this.structuralPermit = structuralPermit;
		this.status = status;
		this.type = type;
	}

	public String toString() {
		return "NewOrder [residentName=" + this.residentName + ", hoaApproval="
				+ this.hoaApproval + ", electricalPermit=" + this.electricalPermit + 
				", structuralPermit=" + this.structuralPermit
				+ ", status=" + this.status + ", type=" + this.type + "]";
	}

	public java.lang.Boolean getStructuralPermit() {
		return this.structuralPermit;
	}

	public void setStructuralPermit(java.lang.Boolean structuralPermit) {
		this.structuralPermit = structuralPermit;
	}

	public java.lang.Boolean getElectricalPermit() {
		return this.electricalPermit;
	}

	public void setElectricalPermit(java.lang.Boolean electricalPermit) {
		this.electricalPermit = electricalPermit;
	}

	public NewOrder(java.lang.String residentName, java.lang.Character type,
			java.lang.Character hoaApproval,
			java.lang.Boolean structuralPermit, java.lang.String status,
			java.lang.Boolean electricalPermit) {
		this.residentName = residentName;
		this.type = type;
		this.hoaApproval = hoaApproval;
		this.structuralPermit = structuralPermit;
		this.status = status;
		this.electricalPermit = electricalPermit;
	}

}