package com.assignment.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Propietario")
	private java.lang.String nombrePropietario;

	@org.kie.api.definition.type.Label("Tipo")
	private java.lang.Character tipo;

	@org.kie.api.definition.type.Label("Aprobacion")
	private java.lang.Character aprobacion;

	@org.kie.api.definition.type.Label("Permiso Estructural")
	private java.lang.Boolean permisoEstructural;

	@org.kie.api.definition.type.Label("Estatus")
	private java.lang.String estatus;

	@org.kie.api.definition.type.Label(value = "Permiso Electrico")
	private java.lang.Boolean permisoElectrico;

	public NewOrder() {
	}

	public java.lang.String getNombrePropietario() {
		return this.nombrePropietario;
	}

	public void setNombrePropietario(java.lang.String nombrePropietario) {
		this.nombrePropietario = nombrePropietario;
	}

	public java.lang.Character getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.Character tipo) {
		this.tipo = tipo;
	}

	public java.lang.Character getAprobacion() {
		return this.aprobacion;
	}

	public void setAprobacion(java.lang.Character aprobacion) {
		this.aprobacion = aprobacion;
	}

	public java.lang.String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(java.lang.String estatus) {
		this.estatus = estatus;
	}

	public java.lang.Boolean getPermisosAprobados() {
		return this.permisoEstructural && this.permisoElectrico;
	}

	public NewOrder(java.lang.Character aprobacion,
			java.lang.Boolean permisoElectrico,
			java.lang.Boolean permisoEstructural, java.lang.String estatus,
			java.lang.String nombrePropietario) {
		this.aprobacion = aprobacion;
		this.permisoElectrico = permisoElectrico;
		this.permisoEstructural = permisoEstructural;
		this.estatus = estatus;
		this.nombrePropietario = nombrePropietario;
	}

	public NewOrder(java.lang.String nombrePropietario,
			java.lang.Character aprobacion, java.lang.Boolean permisoElectrico,
			java.lang.Boolean permisoEstructural, java.lang.String estatus,
			java.lang.Character tipo) {
		this.nombrePropietario = nombrePropietario;
		this.aprobacion = aprobacion;
		this.permisoElectrico = permisoElectrico;
		this.permisoEstructural = permisoEstructural;
		this.estatus = estatus;
		this.tipo = tipo;
	}

	public String toString() {
		return "Nueva Orden [Propietario=" + this.nombrePropietario + ", Aprobacion="
				+ this.aprobacion + ", Permiso Electrico=" + this.permisoElectrico + 
				", Permiso Estructural=" + this.permisoEstructural
				+ ", Estatus=" + this.estatus + ", Tipo=" + this.tipo + "]";
	}

	public java.lang.Boolean getpermisoEstructural() {
		return this.permisoEstructural;
	}

	public void setPermisoEstructural(java.lang.Boolean permisoEstructural) {
		this.permisoEstructural = permisoEstructural;
	}

	public java.lang.Boolean getPermisoElectrico() {
		return this.permisoElectrico;
	}

	public void setPermisoElectrico(java.lang.Boolean permisoElectrico) {
		this.permisoElectrico = permisoElectrico;
	}

	public NewOrder(java.lang.String nombrePropietario, java.lang.Character tipo,
			java.lang.Character aprobacion,
			java.lang.Boolean permisoEstructural, java.lang.String estatus,
			java.lang.Boolean permisoElectrico) {
		this.nombrePropietario = nombrePropietario;
		this.tipo = tipo;
		this.aprobacion = aprobacion;
		this.permisoEstructural = permisoEstructural;
		this.estatus = estatus;
		this.permisoElectrico = permisoElectrico;
	}

}