package com.assignment.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class RequestPermit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PID")
	private java.lang.Integer pid;
	public RequestPermit() {
	}

	public java.lang.Integer getPid() {
		return this.pid;
	}

	public void setPid(java.lang.Integer pid) {
		this.pid = pid;
	}

	public RequestPermit(java.lang.Integer pid) {
		this.pid = pid;
	}

}